---
---

<u>*At present, all meetings are virtual due to COVID-19*</u>

## About

The Computational Demography Working Group (CDWG) at the University of Washington meets weekly to provide an interdisciplinary forum for discussions of digital and computational approaches to demographic research. The workshop features a range of paper presentations, methods demonstrations, software tutorials and professional development. The CDWG is sponsored by the Center for Studies in Demography and Ecology (CSDE), the eScience Institute and OBSSR T32 Grant #1T32HD101442-01. We welcome anyone with interest in computational demography (broadly defined).

## Calendar

<iframe src="https://calendar.google.com/calendar/embed?src=computational-demogr%40uw.edu&ctz=America%2FLos_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>


## CDWG Coordinator
[Zack W. Almquist](http://depts.washington.edu/), Assistant Professor of Sociology and Senior Data Science Fellow, eScience Institute & Core Training Director CSDE





